export const formatId = (id: string) => {
        return id.trim()
                .replace("-","")
                .replace(" ","")
                .replace(" ","")
                .replace(" ","")
                .replace(" ","")
                .replace(" ","")
                .replace(" ","")
                .replace(" ","")
                .replace(" ","")
                .replace(" ","")
                .replace(" ","")
                .replace("&","")
                .replace(".","")
                .replace("/","")
                .replace("'","")
                .replace(":","")
}
 